### ISSUE TITLE
lammps/benz-graph-slc example does not work

### ISSUE THREAD

**Issue by pjuda** [cosmo-epfl/i-pi-dev#220] opened 2018-01-30 15:18 UTC
The example `lammps/benz-graph-slc` fails.
To reproduce, go to `examples/lammps` and use:
`make benz-graph-slc`

This yields the i-PI error:
```
Traceback (most recent call last):
  File "/home/pjuda/bin/i-pi", line 101, in <module>
    main(args[0], options.do_yappi)
  File "/home/pjuda/bin/i-pi", line 48, in main
    simulation = Simulation.load_from_xml(fn_input, request_banner=True)
  File "/home/pjuda/source/i-pi-dev/ipi/engine/simulation.py", line 91, in load_from_xml
    simulation.bind()
  File "/home/pjuda/source/i-pi-dev/ipi/engine/simulation.py", line 160, in bind
    s.bind(self)
  File "/home/pjuda/source/i-pi-dev/ipi/engine/system.py", line 103, in bind
    self.motion.bind(self.ensemble, self.beads, self.nm, self.cell, self.forces, self.prng)
  File "/home/pjuda/source/i-pi-dev/ipi/engine/motion/dynamics.py", line 129, in bind
    raise ValueError("The number of mts levels for the integrator does not agree with the mts_weights of the force components.")
ValueError: The number of mts levels for the integrator does not agree with the mts_weights of the force components.
```

Note: the fixed version of this examples is in the fix-examples branch and will be merged to master in pull request #218

**Comment by mahrossi** [comment] 2018-01-30 15:22
Hello @pjuda , in which branch are you testing this? Master? I noticed that some files have not been synced for this example there.

**Comment by mahrossi** [comment] 2018-01-30 15:27
Update: yes, actually it was working on Friday and now not anymore. What is the new syntax for mts? @ceriottm

**Comment by mahrossi** [comment] 2018-01-30 15:38
Okay, before I could run in nvt mode but use mts_weights. Now one has to specify that the dynamics mode is mts... is that correct? In that case I just add nmts[1,1] as well. Or is there another way of fixing this?

**Comment by pjuda** [comment] 2018-01-30 15:46
The example with all the relevant files (I hope) is in the fix-examples branch. The error can be reproduced using either the code in the master, or the code in the fix-examples branch.

**Comment by venkatkapil24** [comment] 2018-01-30 15:50
Hey Mariana! The problem is that you have specified mts_weights but you have not specified nmts which should be an array of size 2. So I would say just add <nmts> [$,$] </nmts>. Also the mode should be "mts". If you were able to use MTS with mode="nvt" you were probably using a private branch (not part of i-pi-dev)

**Comment by mahrossi** [comment] 2018-02-12 12:35
This has bin fixed in the branch fix-examples

**Closed** 2018-02-12 12:37 UTC
