### ISSUE TITLE
Bug in qtip4pf, ewald term

### ISSUE THREAD

**Issue by litman90** [cosmo-epfl/i-pi-dev#185] opened 2017-05-10 19:13 UTC
I computed the energy of a relaxed water monomer (see below the geometry) and the Ewald term is non-zero (Ewald = -4.3104863337722898E-007 (a.u.) ). In general, it should be inoffensive but it is a bug. In particular, it causes problems if you want to optimize with an energy tolerance below 1e-7.

------------------------------------------------------------------------------------------------------------------------------
water.xyz
3
# CELL(abcABC): 550.18034   550.29206   550.21758   90.00000    90.00000    90.00000  cell{atomic_unit}  Traj: positions{angstrom} Step:           0  Bead:       0 
  O                0.41131003       -0.93977977       -0.11788910
   H               0.13653169       -1.42167286       -0.89038905
   H                1.60777812       -0.97592555       -0.28273782
(with a box of 50x50x50 the result is the same)

**Comment by robeme** [comment] 2017-05-10 19:31
Hej, maybe this is associated with LAMMPS. How do you have calculated the Ewald term? I'm not sure, but I think LAMMPS uses an error of 1e-6 in the example for the Ewald calculations.BestRobertAm 10.05.2017 9:13 nachm. schrieb litman90 <notifications@github.com>:I computed the energy of a relaxed water monomer (see below the geometry) and the Ewald term is non-zero (Ewald = -4.3104863337722898E-007 (a.u.) ). In general, it should be inoffensive but it is a bug. In particular, it causes problems if you want to optimize with an energy tolerance below 1e-7.

water.xyz
3
CELL(abcABC): 550.18034   550.29206   550.21758   90.00000    90.00000    90.00000  cell{atomic_unit}  Traj: positions{angstrom} Step:           0  Bead:       0
O                0.41131003       -0.93977977       -0.11788910
H               0.13653169       -1.42167286       -0.89038905
H                1.60777812       -0.97592555       -0.28273782
(with a box of 50x50x50 the result is the same)

**Comment by robeme** [comment] 2017-05-10 19:36
For reference see:http://lammps.sandia.gov/doc/kspace_style.htmlTypically we used an accuracy of 0.0001 in the LAMMPS inputs.BestRAm 10.05.2017 9:31 nachm. schrieb Robert Meißner <rmei@uni-bremen.de>:Hej, maybe this is associated with LAMMPS. How do you have calculated the Ewald term? I'm not sure, but I think LAMMPS uses an error of 1e-6 in the example for the Ewald calculations.BestRobertAm 10.05.2017 9:13 nachm. schrieb litman90 <notifications@github.com>:I computed the energy of a relaxed water monomer (see below the geometry) and the Ewald term is non-zero (Ewald = -4.3104863337722898E-007 (a.u.) ). In general, it should be inoffensive but it is a bug. In particular, it causes problems if you want to optimize with an energy tolerance below 1e-7.

water.xyz
3
CELL(abcABC): 550.18034   550.29206   550.21758   90.00000    90.00000    90.00000  cell{atomic_unit}  Traj: positions{angstrom} Step:           0  Bead:       0
O                0.41131003       -0.93977977       -0.11788910
H               0.13653169       -1.42167286       -0.89038905
H                1.60777812       -0.97592555       -0.28273782
(with a box of 50x50x50 the result is the same)

**Comment by ceriottm** [comment] 2017-05-10 20:42
Isn't this just the self-interaction between the periodic images?

**Comment by litman90** [comment] 2017-05-10 21:24
Excuse me @robeme  I was talking about qtip4pf in the driver. 
I don't think that is just the self-interaction since I got the same value with two very different box size ( 50^3 and 550^3 )

**Comment by pjuda** [comment] 2017-11-29 13:57
Hi @litman90 ,
We are currently trying to reproduce the issue. Could you explain what do you mean by "Ewald term"? Do you obtain it from the driver's output or do you calculate it (how)?
And if you still have your input file, could you attach it, please?
Thanks in advance :)

**Comment by ceriottm** [comment] 2017-11-29 23:59
Honestly, this is hardly a priority - the driver is really not meant for
serious use but just for demonstration and debugging. The qtip4p
implementation is copied verbatim from an ancient Fortran code from Mano,
Scott & Tom and i don't think they ever really bothered to implement a
robust or efficient version of the Ewald part.

**Comment by litman90** [comment] 2017-12-01 13:14
Sorry for the late answer.
Unfortunately, I don't have the inputs.
The problem was that the reciprocal space part of the Ewald sum didn't have a cut-off for the minimum value. Then, in some extreme conditions, it adds an unwanted noise instead of a zero.
Nothing really serious, but since we were testing the geop routine at that moment I reported it.

**Comment by pjuda** [comment] 2018-01-30 15:00
Thank you, @litman90 for answering. I discussed it with @ceriottm and he decided that fixing this bug is out of scope, since the driver is for demonstration purpose and the problem is minor. Therefore, I close the issue.

**Closed by pjuda** 2018-01-30 15:00 UTC
